### ISSUE TITLE
CMake configuration - problem switching between release and debug build

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#266]
This issue only arises for someone building a local copy of mspass for development who needs to work with the C/C++ library.  It thus should be consider of minor importance for the time being, but I do think it is worth noting.   

A problem has happened when I rebuild the mspass libraries with cmake switching these two lines:
```
set (default_build_type "Release")
#set (default_build_type "Debug")
```
i.e. moving the comment to change back and forth between release and debug.  I've tried both 
```
cmake ..
make
```
and 
```
make clean 
cmake ..
make
```
In both cases turning -g (the main debug flag) on and off does not happen.  The only way I've found to work around the problem is to remove the entire build directory under cxx and build everything from scratch.    

I presume there is some missing magic flag we need to cmake in one or more cmake configuration files to fix this.  I have no clue what it might be, but it has happened to me 3 times now.

**Comment by pavlis** [comment]
Addendum:  note the worst problem this causes is linking fails when there seems to be a mismatch between files with the --coverage on and off.  i.e. I get link errors about gcov functions.

**Comment by wangyinz** [comment]
This is because of the cache behavior of CMake, and it is not something we should address on our side. Usually if a CMakefile is changed, it is safer to remove the whole build and regenerate the build tree. Or, you may refer to the discussion here to remove the caches: https://stackoverflow.com/questions/59879199/how-to-make-cmake-re-run-from-scratch-without-deleting-and-re-creating-the-build
