### ISSUE TITLE
bug in ErrorLogger bindings

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#302]
I uncovered a bug in ErrorLogger that I am not sure how we fix.  I vaguely remember a similar issue a while back but I do not recall the solution.    The bug is this. 

If one uses this construct to catch a MsPASSError it fails on a type error:
```
try:
   code throwing MsPASSError working on data object d
except MsPASSError as err:
  d.elog.log_error(err)
```

The log_error method of ErrorLogger (elog attribute of d above) has this binding code in cxx/python/utility:
```
py::class_<ErrorLogger>(m,"ErrorLogger","Used to post any nonfatal errors without aborting a program of family of parallel programs")
    .def(py::init<>())
    .def(py::init<const ErrorLogger&>())
    .def(py::init<int>())
    .def("set_job_id",&ErrorLogger::set_job_id)
    .def("get_job_id",&ErrorLogger::get_job_id)
    .def("log_error",py::overload_cast<const MsPASSError&>(&ErrorLogger::log_error),"log error thrown as MsPASSError")
    .def("log_error",py::overload_cast<const std::string,const std::string,const ErrorSeverity>(&ErrorLogger::log_error),"log a message at a specified severity level")
    .def("log_verbose",&ErrorLogger::log_verbose,"Log an informational message - tagged as log message")
    .def("get_error_log",&ErrorLogger::get_error_log,"Return all posted entries")
    .def("size",&ErrorLogger::size,"Return number of entries in this log")
    .def("__len__",&ErrorLogger::size,"Return number of entries in this log")
    .def("worst_errors",&ErrorLogger::worst_errors,"Return a list of only the worst errors")
    .def("__getitem__", [](ErrorLogger &self, size_t i) {
      return py::cast(self).attr("get_error_log")().attr("__getitem__")(i);
    })
```
So the binding code has an entry for allowing log_error to receive a MsPASSError object.   The following little test script, however, shows the problem:
```
from mspasspy.ccore.utility import ErrorLogger
from mspasspy.ccore.utility import MsPASSError,ErrorSeverity
err = MsPASSError("foo","bar",ErrorSeverity.Fatal)
logger=ErrorLogger()
logger.log_error(err)
```
Run that and you should get this:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-5c1f6fe830f4> in <module>
----> 1 logger.log_error(err)

TypeError: log_error(): incompatible function arguments. The following argument types are supported:
    1. (self: mspasspy.ccore.utility.ErrorLogger, arg0: mspass::utility::MsPASSError) -> int
    2. (self: mspasspy.ccore.utility.ErrorLogger, arg0: str, arg1: str, arg2: mspasspy.ccore.utility.ErrorSeverity) -> int

Invoked with: <mspasspy.ccore.utility.ErrorLogger object at 0x7fd0af1de3f0>, MsPASSError('foo', 'bar', <ErrorSeverity.Fatal: 0>)
```

This seems to be a symbol mismatch between the C++ namespace symbol `mspass::utility::MsPASSError` and it's pythonic form `mspass.ccore.utility.MsPASSError`  (at least that is what you get if you type `type(err)` with err being the MsPASSError test data created above.  

That construct appears quite a lot in our code base so this represents a serious set of bugs we need to fix asap.   I would do so and submit the change, but you, @wangyinz , are the one who mastered the obscurity of binding C++ classes to python's exception mechanism.

**Comment by wangyinz** [comment]
Yeah, I remember this too. I just found that we had this discussion in #277, but I am not sure why I got it closed without fixing it. Let me give it a try.

**Comment by wangyinz** [comment]
OK, got it fixed in https://github.com/mspass-team/mspass/commit/c9a7a9f191566e98882cd35f67e398e0856e58d2. We can now close this issue. Just a note here the use of `MsPASSError("foo","bar",ErrorSeverity.Fatal)` is wrong. Because our error object implementation is done in cython, it is more flexible that it won't check for the argument count or type. However, our designed use should only be 2 arguments with the first being the message and the second being the severity. When the second arg is `"bar"`, it will actually always recognize it as fatal.

**Comment by pavlis** [comment]
Glad you fixed that.   That usage with 3 string args for the constructor is confusing and we should make sure its usage is clear in the docstring.  Would you check on that?   I didn't check and thought it was the same usage as in the overloaded ErrorLogger.elog.log_error method with 3 strings.  There the args are "algorithm", "message", "badness".  On the other hand I don't think our docs are very good for MsPASSError anyway as it is actually a bound C++object.   Anyway thanks for the prompt fix.

**Comment by wangyinz** [comment]
There is essentially no docstring for the `MsPASSError` exception. The related doc is [here](https://www.mspass.org/python_api/mspasspy.ccore.html#mspasspy.ccore.utility.MsPASSError), and you can see that it is almost empty with only the two members listed. Note that this is actually not a bound C++ object, but an object written with the C extension to Python, and that's why it lacks even the minimum docstrings that we defined for the other bound C++ code. I am actually not quite sure how to add docstrings using the C extension to Python, especially given that the related code is already pretty nasty. Because we simply followed an example we found online, I don't think any of us has mastered the use of the C extension API. 

btw, note that the design of `MsPASSError` is very basic that it only indicates what the error is and how bad it is. The concept of "algorithm" is actually introduced later for the object-level history. That's the main reason why there is no "algorithm" in the `MsPASSError`.
