### ISSUE TITLE
fix needed for normalize module

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#321]
I was working on documentation for the new normalize module.   I realized we had some serious holes in our docstring documentation for all of the subclasses in that file.   I was working through them to fix language issues and fill in missing pieces.   I found what I am pretty sure is a bug in the class `single_key_matcher` when it is applied in the db mode.  
I think the following private method has the bug:
```
    def _db_get_document(self, d):
        query = copy.deepcopy(self.query)

        testid = self._get_key_id(d)
        if testid is None:
            return None
        query["_id"] = testid

        doc = self.dbhandle.find_one(query)
        if doc is None:
            message = "Key [{}] not defined in normalization collection = {}".format(
                str(testid), self.collection
            )
            self.log_error(d, message, ErrorSeverity.Invalid)
            return None

        result = self._load_doc(doc, d)
        return result
```
Seems to me the query creation should be this:
```
query[self.mdkey] = testid
```

I would fix this in the branch for this documentation update, but I'm traveling and cannot test to see if I'm right for about 2 weeks.   It would be better if @wangyinz did a quick fix of this (apparent) bug.  In any case, I think it should be handled.

**Comment by wangyinz** [comment]
I just tried the change you suggest and it breaks the test. Well need to take a closer look on how this works, but my current understanding is that the `testid` is a key in the wf collection such as `channel_id`, and it needs to match with the `_id` key in the channel collection. Is that right?

**Comment by wangyinz** [comment]
OK, I figured it out. This `_db_get_document` method is implemented under `single_key_matcher`, and that's why it doesn't make sense to query for `_id` only. Then, the class is later inherited by `ID_matcher` where it makes sense to match for `_id`. In the test, we only tested for `ID_matcher` so the issue was never revealed (or should I say that we never had the usage of `single_key_matcher` in mind when implementing this). So, I believe we need to fix this line in `single_key_matcher` and then overload it in the `ID_matcher`.
